---
os: linux 
dist: xenial
language: node_js
node_js:
  - "14"
services:
  - docker
before_install:
  - docker pull o2rproject/o2r-loader:latest
  - docker pull o2rproject/o2r-meta:latest
  - docker pull o2rproject/containerit:geospatial
  - docker pull mongo:3.4
  - docker build --file test/Dockerfile . > docker_image_build.log 2>&1
install:
  - npm install
before_script:
  - mkdir -p /tmp/o2r
  - docker run --name mongodb -d -p 27017:27017 mongo:3.4
  - docker run --name testloader      -d -p 8088:8088 --link mongodb:mongodb -v /tmp/o2r:/tmp/o2r -v /var/run/docker.sock:/var/run/docker.sock -e LOADER_MONGODB=mongodb://mongodb:27017      -e DEBUG=* o2rproject/o2r-loader:latest
  - docker build --tag muncher .
  - docker run --name testmuncher     -d -p 8080:8080 --link mongodb:mongodb -v /tmp/o2r:/tmp/o2r -v /var/run/docker.sock:/var/run/docker.sock -e MUNCHER_MONGODB=mongodb://mongodb:27017     -e DEBUG=muncher,muncher:* muncher
  - sleep 10
env:
  - TEST_SET=compendium
  - TEST_SET=download
  - TEST_SET=job
  - TEST_SET=metadata
  - TEST_SET=execution
  - TEST_SET=substitution
script:
  - TEST_JOB_POLL_INTERVAL=10000 npm run-script test_ci
after_failure:
  - sleep 5
  - docker logs testmuncher
  - docker logs testloader
  - cat docker_image_build.log
